use super::*;
use std::time::{Duration, Instant};

#[test]
fn test_dualize_first_quadrant() {
    // First quadrant in 2D: x >= 0, y >= 0
    let hyperplanes = vec![
        vec![1, 0], // x >= 0
        vec![0, 1], // y >= 0
    ];

    let rays = dualize(&hyperplanes, 2);

    // Should get rays (1,0) and (0,1)
    assert_eq!(rays.len(), 2);
    assert!(rays.contains(&vec![1, 0]));
    assert!(rays.contains(&vec![0, 1]));
}

#[test]
#[should_panic(expected = "DDM hyperplane limit exceeded")]
fn test_ddm_hyperplane_limit_panics_with_progress() {
    let limits = DdmLimits {
        max_hyperplanes: Some(3),
        max_time: None,
        start: Instant::now(),
    };

    limits.check(3, 10, 42);
}

#[test]
#[should_panic(expected = "DDM time limit exceeded")]
fn test_ddm_time_limit_panics_with_progress() {
    let limits = DdmLimits {
        max_hyperplanes: None,
        max_time: Some(Duration::ZERO),
        start: Instant::now(),
    };

    limits.check(0, 10, 42);
}

#[test]
fn test_dualize_preserves_ray_orientation() {
    let hyperplanes = vec![
        vec![-1, 0], // x <= 0
        vec![0, 1],  // y >= 0
    ];

    let rays = dualize(&hyperplanes, 2);

    assert_eq!(rays.len(), 2);
    assert!(rays.contains(&vec![-1, 0]));
    assert!(rays.contains(&vec![0, 1]));
    assert!(!rays.contains(&vec![1, 0]));
}

#[test]
fn test_dualize_half_plane() {
    // Half-plane: x >= 0
    let hyperplanes = vec![vec![1, 0]];

    let rays = dualize(&hyperplanes, 2);

    // Should get rays (1,0), (0,1), (0,-1)
    // Because y can be anything, x must be >= 0
    assert!(rays.len() >= 2);
    assert!(rays.contains(&vec![1, 0]));
}

#[test]
fn test_dualize_empty() {
    // No hyperplanes = full space
    let rays = dualize(&[], 2);

    // Should get ±e_i for i in 0..2
    assert_eq!(rays.len(), 4);
}

#[test]
fn test_dualize_single_ray_cone() {
    // Cone generated by single ray (1,1)
    // Dual hyperplanes are: h such that h·(1,1) >= 0
    // i.e., h1 + h2 >= 0
    let rays = vec![vec![1, 1]];
    let hyperplanes = dualize(&rays, 2);

    // Check that (1,1)·h >= 0 for all h
    for h in &hyperplanes {
        let dot: i128 = h.iter().sum();
        assert!(dot >= 0, "Hyperplane {h:?} violates constraint");
    }
}

#[test]
fn test_dualize_with_redundant_input_rays() {
    let rays = vec![
        vec![1, 0],
        vec![0, 1],
        vec![1, 1], // redundant generator in the first quadrant
    ];
    let hyperplanes = dualize(&rays, 2);

    assert!(hyperplanes.iter().any(|h| h == &vec![1, 0]));
    assert!(hyperplanes.iter().any(|h| h == &vec![0, 1]));
    for h in &hyperplanes {
        for r in &rays {
            assert!(
                dot_product(h, r) >= 0,
                "dual hyperplane {h:?} cuts input ray {r:?}"
            );
        }
    }
}

#[test]
fn test_process_hyperplane() {
    // Start with ±e_1, ±e_2 and add x >= 0
    let rays = vec![
        DdmRay {
            coeffs: vec![1, 0],
            active: Vec::new(),
        },
        DdmRay {
            coeffs: vec![-1, 0],
            active: Vec::new(),
        },
        DdmRay {
            coeffs: vec![0, 1],
            active: Vec::new(),
        },
        DdmRay {
            coeffs: vec![0, -1],
            active: Vec::new(),
        },
    ];
    let h = DdmHyperplane::new(vec![1, 0]);

    let mut adjacency_cache = HashMap::new();
    let mut rank_context = RankContext::default();
    let (new_rays, stats) = process_hyperplane(
        &rays,
        &h,
        0,
        &[],
        2,
        false,
        &mut rank_context,
        &mut adjacency_cache,
    );
    assert_eq!(stats.positive, 1);
    assert_eq!(stats.negative, 1);
    let new_rays = new_rays
        .into_iter()
        .map(|ray| ray.coeffs)
        .collect::<Vec<_>>();

    // Should keep (1,0), (0,1), (0,-1) and intersection of (-1,0) with positives
    assert!(new_rays.contains(&vec![1, 0]));
    assert!(new_rays.contains(&vec![0, 1]));
    assert!(new_rays.contains(&vec![0, -1]));
    assert!(!new_rays.contains(&vec![-1, 0]));
}

#[test]
fn test_process_hyperplane_skips_redundant_constraint() {
    let rays = vec![
        DdmRay {
            coeffs: vec![1, 0],
            active: vec![0],
        },
        DdmRay {
            coeffs: vec![0, 1],
            active: vec![1],
        },
    ];
    let h = DdmHyperplane::new(vec![1, 1]);
    let mut adjacency_cache = HashMap::new();
    let mut rank_context = RankContext::default();

    let (new_rays, stats) = process_hyperplane(
        &rays,
        &h,
        2,
        &[],
        2,
        true,
        &mut rank_context,
        &mut adjacency_cache,
    );

    assert!(stats.redundant);
    assert_eq!(new_rays.len(), rays.len());
    assert_eq!(new_rays[0].active, vec![0]);
    assert_eq!(new_rays[1].active, vec![1]);
}

#[test]
fn test_compute_intersection_ray() {
    // pos = (1, 0), neg = (-1, 0), h = (1, 0)
    // h·pos = 1, h·neg = -1
    // r = 1*(-1,0) - (-1)*(1,0) = (-1,0) + (1,0) = (0,0)
    // This is degenerate - correct behavior

    // Better test: pos = (1,1), neg = (-1,1), h = (1,0)
    // h·pos = 1, h·neg = -1
    // r = 1*(-1,1) - (-1)*(1,1) = (-1,1) + (1,1) = (0,2)
    let pos = vec![1, 1];
    let neg = vec![-1, 1];
    let h = DdmHyperplane::new(vec![1, 0]);

    let ray = compute_intersection_ray(&pos, &neg, &h).unwrap();
    assert_eq!(ray, vec![0, 1]); // normalized (0,2) -> (0,1)

    // Verify: h·ray = 0
    let dot = h.dot(&ray);
    assert_eq!(dot, 0);
}

#[test]
fn test_compute_intersection_ray_handles_large_canceling_intermediates() {
    let big = i128::MAX / 2;
    let pos = vec![big, 1];
    let neg = vec![-big, 1];
    let h = DdmHyperplane::new(vec![1, 0]);

    let ray = compute_intersection_ray(&pos, &neg, &h).unwrap();

    assert_eq!(ray, vec![0, 1]);
    assert_eq!(h.dot(&ray), 0);
}

#[test]
fn test_compute_intersection_ray_handles_overflowing_dot_products() {
    let big = i128::MAX / 2 + 1;
    let pos = vec![big, big - 1, 1];
    let neg = vec![-big, -(big - 1), 1];
    let h = DdmHyperplane::new(vec![2, -2, 0]);

    let ray = compute_intersection_ray(&pos, &neg, &h).unwrap();

    assert_eq!(ray, vec![0, 0, 1]);
    assert_eq!(h.dot(&ray), 0);
}

#[test]
fn test_normalize_ray_preserves_direction() {
    assert_eq!(
        normalize_ray_preserving_direction(vec![2, 4, 6]),
        vec![1, 2, 3]
    );
    assert_eq!(
        normalize_ray_preserving_direction(vec![-2, -4, -6]),
        vec![-1, -2, -3]
    );
    assert_eq!(
        normalize_ray_preserving_direction(vec![0, -2, 4]),
        vec![0, -1, 2]
    );
}

#[test]
fn test_sparse_hyperplane_dot_matches_dense_dot() {
    let dense = vec![0, 3, 0, -5, 0, 2];
    let ray = vec![7, 11, 13, 17, 19, 23];
    let hyperplane = DdmHyperplane::new(dense.clone());

    assert_eq!(hyperplane.sparse, vec![(1, 3), (3, -5), (5, 2)]);
    assert_eq!(hyperplane.dot(&ray), dot_product(&dense, &ray));
}

#[test]
fn test_sparse_hyperplane_dot_sign_falls_back_after_i128_overflow() {
    let big = i128::MAX / 2 + 1;
    let hyperplane = DdmHyperplane::new(vec![2, -2]);

    assert_eq!(
        hyperplane.dot_sign(&[big, big - 1]),
        std::cmp::Ordering::Greater
    );
    assert_eq!(hyperplane.dot_sign(&[big, big]), std::cmp::Ordering::Equal);
    assert_eq!(
        hyperplane.dot_sign(&[big - 1, big]),
        std::cmp::Ordering::Less
    );
}

#[test]
fn test_rank_tracker_exact_rank() {
    let mut rank = RankTracker::new(3);
    rank.add_row(&[1, 2, 3]);
    rank.add_row(&[2, 4, 6]);
    assert_eq!(rank.rank(), 1);
    rank.add_row(&[0, 1, 0]);
    assert_eq!(rank.rank(), 2);
    rank.add_row(&[0, 0, 1]);
    assert_eq!(rank.rank(), 3);
}

#[test]
fn test_active_rank_modular_precheck() {
    let hyperplanes = hyperplanes_from_dense(vec![vec![1, 0, 0], vec![0, -1, 0], vec![0, 0, 1]]);
    assert!(active_rank_mod_prime_at_least(
        &[0, 1, 2],
        &hyperplanes,
        3,
        3
    ));
}

#[test]
fn test_active_rank_exact_fallback_after_modular_drop() {
    let hyperplanes = hyperplanes_from_dense(vec![vec![RANK_MODULUS, 0], vec![0, 1]]);

    assert!(!active_rank_mod_prime_at_least(&[0, 1], &hyperplanes, 2, 2));
    let mut stats = RankStats::default();
    let mut rank_context = RankContext::default();
    assert!(active_rank_at_least(
        &[0, 1],
        &hyperplanes,
        2,
        2,
        &mut rank_context,
        &mut stats
    ));
}

#[test]
fn test_intersection_active_set_is_common_active_plus_new_hyperplane() {
    let p = DdmRay {
        coeffs: vec![1, 0],
        active: vec![0, 1, 3],
    };
    let n = DdmRay {
        coeffs: vec![0, 1],
        active: vec![1, 2, 3],
    };

    assert_eq!(active_set_for_intersection(&p, &n, 4), vec![1, 3, 4]);
}

#[test]
fn test_basis_prefix_rank_fast_path() {
    let hyperplanes = hyperplanes_from_dense(vec![
        vec![1, 0, 0],
        vec![0, 1, 0],
        vec![0, 0, 1],
        vec![1, 1, 1],
    ]);

    let mut stats = RankStats::default();
    let basis_dense = dense_prefix(&hyperplanes, 3);
    let mut rank_context = rank_context_for_basis(&basis_dense);
    assert!(active_rank_at_least(
        &[0, 1, 3],
        &hyperplanes,
        3,
        2,
        &mut rank_context,
        &mut stats
    ));
    assert_eq!(stats.basis_hits, 1);
    assert_eq!(stats.integer_checks, 0);
}

#[test]
fn test_quotient_rank_handles_modular_false_true_case() {
    let p = RANK_MODULUS;
    let hyperplanes = hyperplanes_from_dense(vec![
        vec![p, 0, 0],
        vec![0, 1, 0],
        vec![0, 0, 1],
        vec![0, 1, 0],
    ]);
    assert!(!active_rank_mod_prime_at_least(&[0, 3], &hyperplanes, 3, 2));

    let mut stats = RankStats::default();
    let basis_dense = dense_prefix(&hyperplanes, 3);
    let mut rank_context = rank_context_for_basis(&basis_dense);
    assert!(active_rank_at_least(
        &[0, 3],
        &hyperplanes,
        3,
        2,
        &mut rank_context,
        &mut stats
    ));
    assert_eq!(stats.quotient_true, 1);
    assert_eq!(stats.integer_checks, 0);
}

#[test]
fn test_quotient_rank_one_exact_handles_modular_zero_coordinate() {
    let p = RANK_MODULUS;
    let hyperplanes = hyperplanes_from_dense(vec![vec![1, 0], vec![0, 1], vec![0, p]]);
    assert!(!active_rank_mod_prime_at_least(&[0, 2], &hyperplanes, 2, 2));

    let mut stats = RankStats::default();
    let basis_dense = dense_prefix(&hyperplanes, 2);
    let mut rank_context = rank_context_for_basis(&basis_dense);
    assert!(active_rank_at_least(
        &[0, 2],
        &hyperplanes,
        2,
        2,
        &mut rank_context,
        &mut stats
    ));
    assert_eq!(stats.quotient_true, 1);
    assert_eq!(stats.integer_checks, 0);
}

#[test]
fn test_quotient_rank_two_exact_handles_modular_zero_true_case() {
    let p = RANK_MODULUS;
    let hyperplanes = hyperplanes_from_dense(vec![
        vec![1, 0, 0],
        vec![0, 1, 0],
        vec![0, 0, 1],
        vec![0, p, 0],
        vec![0, 0, p],
    ]);
    assert!(!active_rank_mod_prime_at_least(
        &[0, 3, 4],
        &hyperplanes,
        3,
        3
    ));

    let mut stats = RankStats::default();
    let basis_dense = dense_prefix(&hyperplanes, 3);
    let mut rank_context = rank_context_for_basis(&basis_dense);
    assert!(active_rank_at_least(
        &[0, 3, 4],
        &hyperplanes,
        3,
        3,
        &mut rank_context,
        &mut stats
    ));
    assert_eq!(stats.quotient_true, 1);
    assert_eq!(stats.integer_checks, 0);
}

#[test]
fn test_quotient_rank_two_exact_handles_modular_zero_false_case() {
    let p = RANK_MODULUS;
    let hyperplanes = hyperplanes_from_dense(vec![
        vec![1, 0, 0],
        vec![0, 1, 0],
        vec![0, 0, 1],
        vec![0, p, 0],
        vec![0, 2 * p, 0],
    ]);
    assert!(!active_rank_mod_prime_at_least(
        &[0, 3, 4],
        &hyperplanes,
        3,
        3
    ));

    let mut stats = RankStats::default();
    let basis_dense = dense_prefix(&hyperplanes, 3);
    let mut rank_context = rank_context_for_basis(&basis_dense);
    assert!(!active_rank_at_least(
        &[0, 3, 4],
        &hyperplanes,
        3,
        3,
        &mut rank_context,
        &mut stats
    ));
    assert_eq!(stats.quotient_false, 1);
    assert_eq!(stats.integer_checks, 0);
}

#[test]
fn test_quotient_rank_uses_modular_true_certificate() {
    let work = vec![vec![Integer::from(0), Integer::from(1)]];
    assert!(quotient_rank_mod_prime_at_least(&work, 2, 1));
}

#[test]
fn test_integer_mod_prime_handles_negative_values() {
    assert_eq!(integer_mod_prime(&Integer::from(-1)), RANK_MODULUS - 1);
    assert_eq!(integer_mod_prime(&Integer::from(RANK_MODULUS + 3)), 3);
}

#[test]
fn test_quotient_rank_handles_modular_false_false_case() {
    let p = RANK_MODULUS;
    let hyperplanes = hyperplanes_from_dense(vec![
        vec![p, 0, 0],
        vec![0, 1, 0],
        vec![0, 0, 1],
        vec![2 * p, 0, 0],
    ]);
    assert!(!active_rank_mod_prime_at_least(&[0, 3], &hyperplanes, 3, 2));

    let mut stats = RankStats::default();
    let basis_dense = dense_prefix(&hyperplanes, 3);
    let mut rank_context = rank_context_for_basis(&basis_dense);
    assert!(!active_rank_at_least(
        &[0, 3],
        &hyperplanes,
        3,
        2,
        &mut rank_context,
        &mut stats
    ));
    assert_eq!(stats.quotient_false, 1);
    assert_eq!(stats.integer_checks, 0);
}

#[test]
fn test_initial_basis_prunes_redundant_remaining_hyperplanes() {
    let hyperplanes = vec![
        vec![1, 0],
        vec![0, 1],
        vec![1, 1],  // redundant against x >= 0, y >= 0
        vec![-1, 1], // cuts the initial basis cone
    ];

    let (_rays, ordered, start_idx, _rank, _context) =
        initialize_ddm(&hyperplanes, 2).expect("basis initialization succeeds");

    assert_eq!(start_idx, 2);
    assert_eq!(ordered.len(), 3);
    assert_eq!(ordered[0].dense(), &[1, 0]);
    assert_eq!(ordered[1].dense(), &[0, 1]);
    assert_eq!(ordered[2].dense(), &[-1, 1]);
}

#[test]
fn test_current_cone_pruning_removes_newly_redundant_tail_rows() {
    let rays = vec![
        DdmRay {
            coeffs: vec![1, 0],
            active: vec![0],
        },
        DdmRay {
            coeffs: vec![0, 1],
            active: vec![1],
        },
    ];
    let mut hyperplanes = hyperplanes_from_dense(vec![
        vec![1, 0],
        vec![0, 1],
        vec![1, 1],  // redundant against the current cone
        vec![-1, 1], // still cuts the current cone
        vec![2, 3],  // redundant against the current cone
    ]);

    let pruned = prune_current_redundant_hyperplanes(&mut hyperplanes, 2, &rays);

    assert_eq!(pruned, 2);
    assert_eq!(hyperplanes.len(), 3);
    assert_eq!(hyperplanes[0].dense(), &[1, 0]);
    assert_eq!(hyperplanes[1].dense(), &[0, 1]);
    assert_eq!(hyperplanes[2].dense(), &[-1, 1]);
}

#[test]
fn test_remaining_hyperplanes_order_cheapest_initial_cuts_first() {
    let initial_rays = vec![
        DdmRay {
            coeffs: vec![1, 0],
            active: vec![0],
        },
        DdmRay {
            coeffs: vec![0, 1],
            active: vec![1],
        },
    ];
    let hyperplanes = vec![
        vec![1, 0],
        vec![0, 1],
        vec![-1, 1],
        vec![-1, 0],
        vec![1, -1],
    ];
    let selected = vec![true, true, false, false, false];

    let (ordered, pruned) = order_remaining_hyperplanes(&hyperplanes, &selected, &initial_rays);

    assert_eq!(pruned, 0);
    assert_eq!(ordered[0].dense(), &[-1, 0]);
    assert_eq!(ordered[1].dense(), &[-1, 1]);
    assert_eq!(ordered[2].dense(), &[1, -1]);
}

#[test]
fn test_choose_next_hyperplane_prefers_face_collapse() {
    let rays = vec![
        DdmRay {
            coeffs: vec![1, 0],
            active: vec![0],
        },
        DdmRay {
            coeffs: vec![0, 1],
            active: vec![1],
        },
    ];
    let hyperplanes = hyperplanes_from_dense(vec![
        vec![-1, 1], // one positive and one negative ray
        vec![-1, 0], // no positive ray, collapses to a face
    ]);

    assert_eq!(choose_next_hyperplane(&hyperplanes, 0, &rays), 1);
}

#[test]
fn test_choose_next_hyperplane_prefers_cut_over_redundant_row() {
    let rays = vec![
        DdmRay {
            coeffs: vec![1, 0],
            active: vec![0],
        },
        DdmRay {
            coeffs: vec![0, 1],
            active: vec![1],
        },
    ];
    let hyperplanes = hyperplanes_from_dense(vec![
        vec![1, 1],  // redundant against the current cone
        vec![-1, 1], // cuts the current cone
    ]);

    assert_eq!(choose_next_hyperplane(&hyperplanes, 0, &rays), 1);
}

#[test]
fn test_choose_next_hyperplane_expands_past_expensive_local_cut() {
    let rays = vec![
        DdmRay {
            coeffs: vec![1, 0],
            active: vec![0],
        },
        DdmRay {
            coeffs: vec![0, 1],
            active: vec![1],
        },
        DdmRay {
            coeffs: vec![1, 1],
            active: vec![0, 1],
        },
    ];
    let hyperplanes = hyperplanes_from_dense(vec![
        vec![-1, 1], // local cut with positive and negative rays
        vec![1, -1], // local cut with positive and negative rays
        vec![-1, 0], // face collapse just outside the base window
    ]);

    assert_eq!(
        choose_next_hyperplane_with_window(&hyperplanes, 0, &rays, 2, 3, 0),
        2
    );
}

#[test]
fn test_parse_pair_log_interval() {
    assert_eq!(parse_pair_log_interval("250000"), Some(250_000));
    assert_eq!(parse_pair_log_interval("0"), None);
    assert_eq!(parse_pair_log_interval("not-a-number"), None);
}

#[test]
fn test_adjacency_filter_for_pointed_cone() {
    let processed = vec![
        vec![1, 0, 0, 0],
        vec![0, 1, 0, 0],
        vec![0, 0, 1, 0],
        vec![0, 0, 0, 1],
    ];
    let p = DdmRay {
        coeffs: vec![1, 0, 0, 0],
        active: vec![0, 1, 2],
    };
    let adjacent = DdmRay {
        coeffs: vec![0, 1, 0, 0],
        active: vec![0, 1, 3],
    };
    let non_adjacent = DdmRay {
        coeffs: vec![0, 0, 1, 0],
        active: vec![3],
    };

    assert!(are_adjacent(&p, &adjacent, &processed, 4));
    assert!(!are_adjacent(&p, &non_adjacent, &processed, 4));
}

fn rank_context_for_basis(basis: &[Vec<i128>]) -> RankContext {
    let basis_rational: Vec<Vec<Rational>> = basis
        .iter()
        .map(|row| {
            row.iter()
                .map(|&x| Rational::from(Integer::from(x)))
                .collect()
        })
        .collect();
    let inverse = invert_matrix(&basis_rational).expect("test basis is invertible");
    RankContext::with_basis_inverse(&inverse).expect("test inverse scales to integers")
}

fn dense_prefix(hyperplanes: &[DdmHyperplane], len: usize) -> Vec<Vec<i128>> {
    hyperplanes
        .iter()
        .take(len)
        .map(|row| row.dense().to_vec())
        .collect()
}
